// Generated by CoffeeScript 1.4.0
(function() {
  var Fs, Path;

  Fs = require('fs');

  Path = require('path');

  module.exports = function(robot) {
    var path;
    path = Path.resolve(__dirname, 'src');
    return Fs.exists(path, function(exists) {
      var file, _i, _len, _ref, _results;
      if (exists) {
        _ref = Fs.readdirSync(path);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          file = _ref[_i];
          _results.push(robot.loadFile(path, file));
        }
        return _results;
      }
    });
  };

}).call(this);
